### PR TITLE
fix dvar name in player movement

### PR DESCRIPTION
**Pull request by diamante0018**
Addresses parts of #61 (do not close yet)
**How does this PR change IW4x's behaviour?**

Breaking: change dvar name (necessary to avoid bad confusion as it did in the past: bg(both games) name will lead someone who is familiar with quake engine to think that dvar is checked by server side when it is NOT and must cheat protected because it is CG category (client game)

Are there any breaking changes? Will any existing behaviour change?
Yes: above there is an explanation

**Anything else we should know?**
no
Add any other context about your changes here.

### CODE REVIEW

**Comment by Rackover** [comment]
i'm thinking maybe this should have been Weapon.cpp too . . .   i  didn't really put it in the right place at all

**Comment by diamante0018** [comment]
I see, would you like me to move the dvar via this pull request to the other cpp file?

**Comment by Rackover** [comment]
Yes if that's OK i think that would be a good idea while we're here

**Comment by diamante0018** [comment]
Waiting on CI... All is done

**Comment by diamante0018** [comment]
fixed my PR should be good now

**Comment by Rackover** [comment]
will be testing it shortly and then i'll merge it

**Comment by diamante0018** [comment]
Did testing go well?

**Comment by Rackover** [comment]
i don't know, did it?

**Comment by Rackover** [comment]
Works as intended

**Review by Rackover — APPROVED** [review]

**Pull request merged**
